AllCops:
  DisplayCopNames: true
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'config/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/*.rb'
    - 'bin/**/*'
    - Gemfile
    - Rakefile
  
Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false
