language: ruby
sudo: true

rvm:
 - 2.2.6

services:
  - postgresql

before_install:
  - gem update --system
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
  - xvfb-run -a bundle exec rspec
