# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 68272e8df888509c0ff3d088c533d7f1508ac0713994e0bbaa798314e7afc9dd2e59d882d4d3735196c0340b8286336d5453989c35a9e62d5bfe949d51d34f88
  facebook_app_id: 180024532567243
  facebook_app_secret: 6d6923d0f0d92477c624f3d4f8e8ae84

test:
  secret_key_base: 66c7dc2c8d2df446a64bc612a0d9152cf729edd4bb08a6c360672022637b33d50ce769779002e6b2084b4abfb9529ec53f7eeda920971c638e7098341419bb28

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
